### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tsm020** [OlympicCode/vHackAPI-Python#10]
Traceback <most recent call>:
   File "'main.py' , line 160 in <module>
indexerror: string index out of range

Message on discord

**Comment by vBlackOut** [comment]
you use windows or linux ?

**Comment by Tsm020** [comment]
windows

**Comment by vBlackOut** [comment]
ok wait the last day for the check the version

**Comment by Tsm020** [comment]
you did help me last time with teamviewer.
i had that weird system, the bot works.
but when i say no booster, no netcoin, no upgrade then it show this error

**Comment by knightsun** [comment]
hey vblack i closed the last issue of error but stuck again in update loop any help

**Comment by knightsun** [comment]
please guide me if missing any package or json
linux
