### ISSUE TITLE
issue with main.py

### ISSUE THREAD

**Issue by ALENBERG1** [OlympicCode/vHackAPI-Python#12]
file "main.py", line 163,in <module>
keyerror: 'data'

**Comment by vBlackOut** [comment]
you use windows or linux ?

**Comment by ALENBERG1** [comment]
windows my buddy

**Comment by vBlackOut** [comment]
you use main.exe ?

**Comment by ALENBERG1** [comment]
yes

**Comment by ALENBERG1** [comment]
vblackout now the bot work, i don't know why did that before

**Comment by vBlackOut** [comment]
ok great ;)

**Comment by ALENBERG1** [comment]
can i recommend something about a function of bot?

**Comment by vBlackOut** [comment]
You can always be if I have time I would improve

**Comment by ALENBERG1** [comment]
ok, can you add that the bot, every hour, hack the dev? and can you accept my friendship? XD
