### ISSUE TITLE
Linux Error

### ISSUE THREAD

**Issue by DeadlyByNite** [OlympicCode/vHackAPI-Python#15]
> python main.py
> best list for tournament :
> Traceback (most recent call last):
>   File "main.py", line 254, in <module>
>     if "DDoS not ready" in checkcluster["ddosready"] and test == "no":
> TypeError: 'int' object has no attribute '__getitem__'

If I change line 28 in main.py from active_cluster_protection = True to active_cluster_protection = False I get the exact same error, but when I change line 50 in main.py from ddos_cluster = True to ddos_cluster = False I get this error

> python main.py
> analysing configuration... botnet
> updating ipsp level +1
> Waiting... in update
> Packing IP list 6
> Traceback (most recent call last):
>   File "main.py", line 390, in <module>
>     c.attack(attacks_normal, maxanti_normal, wait_load, mode, api, active_cluster_protection)
>   File "/home/deadlybynite/Git/vHackAPI-Python/console.py", line 404, in attack
>     data = self.getIP(True, max, mode, api, active_protecte_cluster_ddos)
>   File "/home/deadlybynite/Git/vHackAPI-Python/console.py", line 196, in getIP
>     wait_for = executor.submit(self.calc_img, ut, list_image[i], uhash, list_hostname[i], max, mode, api)
> NameError: global name 'ut' is not defined

I've tried changing both lines to false since I am not in a cluster, but either way, I keep getting an error. I'm not currently in a cluster, and I believe I need to change some things inside main.py, but not sure what.
 Any help is greatly appreciated!

**Comment by vBlackOut** [comment]
Uh weird i recheck the code dev WookieNZ

**Comment by vBlackOut** [comment]
please redownload the new code it's fix

**Comment by vBlackOut** [comment]
i close the ticket for long time
