### ISSUE TITLE
Analysing Botnet

### ISSUE THREAD

**Issue by rarelogics** [OlympicCode/vHackAPI-Python#22]
Hello,

It does'nt seem to work with me on windows. 
It keeps repeating: 

Analysing Configuration... Botnet
Waiting...
Waiting...
Analysing Configuration... Botnet

And so on. 

What to do?

**Comment by vBlackOut** [comment]
please retest for check the validity file.
i'm back on the projet :)

**Comment by vBlackOut** [comment]
i updated
