### ISSUE TITLE
Needs Improvements.

### ISSUE THREAD

**Issue by sikkina** [OlympicCode/vHackAPI-Python#23]
The bot isn't using boosters. Although this may not affect low upgrade levels, it is crucial for higher level upgrades.
Daily mission prizes should be collected.
The developer should be hacked once in an hour for maximum prizes. 
An improvement towards the cluster function should be added (such as attacking other clusters).

Other than that it is a very good bot which does its job.

p.s, when boosters were working, the bot used to use boosters after each upgrade, so basically wasting a lot of boosters for nothing, instead of after the max upgrades

**Comment by vBlackOut** [comment]
you use windows or linux ?

**Comment by sikkina** [comment]
Windows

**Comment by vBlackOut** [comment]
ok the code on the windows is not fully worked

**Comment by vBlackOut** [comment]
i updated
