### ISSUE TITLE
Upgrades only happen at the beginning of the script

### ISSUE THREAD

**Issue by setnev** [OlympicCode/vHackAPI-Python#3]
Upgrades only happen at the beginning of the script. When I use my netcoins to finish tasks, it never initiates upgrades again unless i run the script over.

**Comment by vBlackOut** [comment]
hmm weird i'm check

**Comment by vBlackOut** [comment]
the script inital loop for 3x attack in console and reinitiale the update.
3x(6) target in console = 18 attack total and recheck the update

**Comment by setnev** [comment]
I let the script run overnight and upgrades never happened automatically. I
checked my upgrade levels after initiating the script and they remained the
same throughout the night. In the morning when I checked, there were no
active running tasks and my upgrade levels were the same as when I left it
overnight.

**Comment by ghost** [comment]
HI,
how version u use? Windows .exe or python on Linux?
It's possible to have a look into ur .ini file (for windows) or main.py (for Linux)?
** REMINDER: Delete ur PW and NICK befor post ur files **

Did u change something other?

Cheers

**Comment by setnev** [comment]
I am using the Windows exe. I have attached my ini file

**Comment by vBlackOut** [comment]
i'm fixed ;)
