### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by wayne1313** [OlympicCode/vHackAPI-Python#34]
Win - short text "Traceback ( most recent ................"

What to do to fix this problem ?

**Comment by vBlackOut** [comment]
Hello, for windows please install python and execute main.py
the verson on windows (main.exe) i don't updated ( i no time srry )

**Comment by Sprite140** [comment]
Can you explain step by step? Because I have been trying to open the file inn python and it has been closing very quickly. Do i need to type something in the python command?

**Comment by wayne1313** [comment]
Same problem as me. Very short text begining with "Traceback............" appearing and then the window closes instant

**Comment by Sprite140** [comment]
I got the termux version to work on my android but it doesn't really do much .. that's why I want to do this version with python to see if there can more done.. it just won't open to even let me type my password and username in.

**Comment by JasonKhew96** [comment]
edit `config.py` username and password, you may want to join [discord](https://discord.gg/EZNjh7t) for more support and news.

**Comment by wayne1313** [comment]
I already edited config.py
I inserted my username and my password between the both "...." and "....."

Still the same problem of very fast closing the main.py

My Username contains a _ . Could that be a problem ?

**Comment by vBlackOut** [comment]
please look here
https://www.howtogeek.com/197947/how-to-install-python-on-windows/
install python2.7
edit config.py and execute the main.py by the python

**Comment by wayne1313** [comment]
I did this

**Comment by wayne1313** [comment]
even tried with v3 of Phyton

**Comment by vBlackOut** [comment]
please connect discord i look with you

**Comment by vBlackOut** [comment]
https://discord.gg/uGVkY6 link

**Comment by wayne1313** [comment]
in about 11h I'll be @home. then I connect with you on discord. okay ?

**Comment by vBlackOut** [comment]
ok where your live ? i live in france it's 12:00PM for me

**Comment by wayne1313** [comment]
Same for me, but I am from Germany

**Comment by vBlackOut** [comment]
ok no problem :)
on discord my nickname is vBlackOut and have the blue skeleton on the picture

**Comment by wayne1313** [comment]
Thank you for personal look at me beeing to silly to run it in cmd. MY FAULT !


Thank you so much
