### ISSUE TITLE
Bot Crash (BotNet Update)

### ISSUE THREAD

**Issue by AtjonTV** [OlympicCode/vHackAPI-Python#44]
I was running the bot for 11hrs and now i created a bot net and after i created it i saw that the bot didnt work, i logged into the terminal and i got the same error as below (i cleared the terminal and restarted the bot)

![screenshot from 2017-12-29 14 19 46](https://user-images.githubusercontent.com/24845056/34438014-ba482be4-eca3-11e7-9817-2cfca45f9d70.png)

**Comment by AtjonTV** [comment]
After changing the botnet.py functions upgradebotnet and upgradesinglebot to the following it started a permanent loop with "Prepare attempting to upgrade bot net PC's <name> [<what>]"

![screenshot from 2017-12-29 14 38 00](https://user-images.githubusercontent.com/24845056/34438274-e7548630-eca5-11e7-8fe8-be33dbb3d0dc.png)

**Comment by AtjonTV** [comment]
And something else .. i found this code:
>elif (int(get_infobot['energy']) > 0):
>logger.info("your are not energy for update " + hostname + " :(")
>return False

so whenever the energy is above 0 its not enough (should be fixed)

**Comment by JasonKhew96** [comment]
`upgradesinglebot` function didn't have `count` parameter.

**Comment by AtjonTV** [comment]
even with (I called it 'id') its entering a loop "Prepare attempting to upgrade bot net PC's -name- [-what-]"

heres a screenshot:

![screenshot from 2017-12-29 15 19 38](https://user-images.githubusercontent.com/24845056/34439072-b9ae64d4-ecab-11e7-93cc-c3b2ff0ceed6.png)

**Comment by AtjonTV** [comment]
Ah .. I see where the problem is .. the `upgradesinglebot` function just calls itself instead of upgrading (line 150 in botnet.py)

**Comment by vBlackOut** [comment]
you have change your **upgradesinglebot** function the original is here 
https://github.com/OlympicCode/vHackXTBot-Python/blob/master/botnet.py#L135

 > never use "id" in **upgradesinglebotnet** 

and original  **upgradebotnet** function is here
https://github.com/OlympicCode/vHackXTBot-Python/blob/master/botnet.py#L93

Please redownload the bot and run.

**Comment by AtjonTV** [comment]
As soon as i do i get the error that `upgradesinglebot` needs 4 args (line 108 and 150

**Comment by vBlackOut** [comment]
ok please connect you on discord channel https://discord.gg/EZNjh7t
