### ISSUE TITLE
add option to select botnet upgrades?

### ISSUE THREAD

**Issue by NidPlays** [OlympicCode/vHackAPI-Python#49]
title says it all

**Comment by AtjonTV** [comment]
like the selection used on account upgrades?

Example `config.py` section:
```python
# update botnet auto
BotNet_update = True
# Enter Updates (fw, av, smash, mwk)
BotNet_updates =["fw", "av", "smash", "mwk"]
```

fw = Firewall
av = Antivirus
smash = Remote Smash
mwk = Malware Kit

**Comment by Gond0r** [comment]
options are ['smash', 'mwk', 'fw', 'av']

**Comment by NidPlays** [comment]
yeah like that

**Comment by AtjonTV** [comment]
Okay .. I'll see if i can implement that; should not be that hard :smile:

**Comment by AtjonTV** [comment]
Okay .. I made some changes, and it works on my PC

Repo is ready for Pull :smile:

**Comment by AtjonTV** [comment]
Issue resolved, please close this issue :D

**Comment by NidPlays** [comment]
Thanks for the work
