### ISSUE TITLE
Linux Bug Report

### ISSUE THREAD

**Issue by DeadlyByNite** [OlympicCode/vHackAPI-Python#5]
analyse configuration... botnet
No money to update Botnet #4
No money to update Botnet #5
No money to update Botnet #6
No money to update Botnet #7
No money to update Botnet #8
Update Botnet 9 level : 2
No money to update Botnet #9
Waiting... in normal 2.03s
Traceback (most recent call last):
  File "./main.py", line 206, in <module>
    c.attack(attacks_normal, maxanti_normal, wait_load, mode, api, active_cluster_protection)
  File "/home/deadlybynite/Git/vHackAPI-Python/console.py", line 396, in attack
    data = self.getIP(True, max, mode, api, active_protecte_cluster_ddos)
  File "/home/deadlybynite/Git/vHackAPI-Python/console.py", line 168, in getIP
    if stat_cluter_blocked == stat_cluster['blocked']:
TypeError: 'int' object has no attribute '__getitem__'

**Comment by vBlackOut** [comment]
wait i'm check ;)

**Comment by vBlackOut** [comment]
ok i'm fix on the last update ;) redownload

**Comment by DeadlyByNite** [comment]
Working perfectly now! Thanks for the quick fix!
