### ISSUE TITLE
Import PIL | no module named PIL| last version

### ISSUE THREAD

**Issue by NandoPrates** [OlympicCode/vHackAPI-Python#52]
[root@centos7tpl vHackXTBot-Python]# python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from console import Console
  File "/root/vHackXTBot-Python/console.py", line 8, in <module>
    from PIL import Image
ImportError: No module named PIL
[root@centos7tpl vHackXTBot-Python]#

**Comment by AtjonTV** [comment]
Did you install the Python Imaging Library (PIL)?

For CentOS:
```
yum install python-imaging
```

or use Python-PIP and the requirements file
```
pip install -r requirements.txt
```

or this Script (Not Tested!)
```
https://github.com/AtjonTV/vHackBot-install/blob/master/install-centos.sh
```

**Comment by NandoPrates** [comment]
O solve using pip2 install -r requirements.txt
"Pip" for python 3.5
Pip2 for python 2.7

**Comment by vBlackOut** [comment]
or for python2 explicite pip install
```
python2 -m pip install -r requirements.txt
```
No problem you are welcome :D now \o/
