### ISSUE TITLE
having this kind of issue when running.

### ISSUE THREAD

**Issue by ghost** [OlympicCode/vHackAPI-Python#54]
Help would be appreciated.
Using the latest version of Python.
Windows 10.

Traceback (most recent call last):
  File "G:\Media\Compressed\vHackXTBot-Python-master\utils.py", line 92, in md5hash
    m.update(txt)
TypeError: Unicode-objects must be encoded before hashing

Edit:
Managed to fix this error, but another pops out:
File "G:\Media\Compressed\vHackXTBot-Python-master\utils.py", line 161, in requestString
    except urllib.URLError as e:
AttributeError: module 'urllib' has no attribute 'URLError'

Edit 2: fixed it by adding .error. between the urllib and URLError.
Afterwards, I get this error:

a bytes-like object is required, not 'str'
and loops.

**Comment by JasonKhew96** [comment]
@JustAViewer 
[vHackXTBot-Python](https://github.com/OlympicCode/vHackXTBot-Python) is currently outdated.
Use [vHackOSBot-Java](https://github.com/OlympicCode/vHackOSBot-Java) if you want.

**Comment by vBlackOut** [comment]
the bot don't work for python3 please just install python2.7 please read the readme
