### ISSUE TITLE
botnet update faild

### ISSUE THREAD

**Issue by nikoomaram** [OlympicCode/vHackAPI-Python#55]
hi
botnet update only say faild!

logger.error("Upgrades on " + hostname + " Failed !")

**Comment by nikoomaram** [comment]
Anyone!?

**Comment by CiloxQ** [comment]
Hey Nikoomaram!

**Comment by CiloxQ** [comment]
Need your help, can we talk private?

**Comment by nikoomaram** [comment]
Hey
Yes we can .
What's happening?

**Comment by CiloxQ** [comment]
I don't have line anymore, what your email? or you could just send me a mail to ciloxng@gmail.com
