### ISSUE TITLE
Windows Bug

### ISSUE THREAD

**Issue by aladin221** [OlympicCode/vHackAPI-Python#6]
Does not work on Windows 7

C:\Users\test\Desktop\vHackAPI-Python-master\vHackAPI-Python-master\Windows>main.exe
your Username : userxyz
Your Password : ********
loading ...C:\Users\test\Desktop\vHackAPI-Python-master\vHackAPI-Python-master\Windows\config.ini
Traceback (most recent call last):
  File "main.py", line 156, in <module>
IndexError: string index out of range

**Comment by vBlackOut** [comment]
what is your config.ini
the problme is on the file
please send me your file

**Comment by aladin221** [comment]
i'm not change anything

[Config]
maxanti_normal: 3000
maxanti_tournament: 3000
booster: True
Use_netcoins: True
attacks_normal: 3
attacks_tournament: 2
tournament_potator: True
update: None
join_tournament: True
mode: Potator
Botnet_update: True

**Comment by vBlackOut** [comment]
ok please connect here for send me descript your detail 
https://discordapp.com/channels/219254781384851467/219254781384851467

**Comment by aladin221** [comment]
i can't found you there

**Comment by vBlackOut** [comment]
my name is vBlackOut in contributor

**Comment by vBlackOut** [comment]
what is your pseudo ?

**Comment by aladin221** [comment]
its say me "We need vBlackOut's four digit tag so we know which one they are."

**Comment by vBlackOut** [comment]
hum check this link
https://discordapp.com/channels/219254781384851467/219254781384851467

**Comment by aladin221** [comment]
try to find me its not work . my name there is aladin2207

**Comment by vBlackOut** [comment]
#8184 my identification

**Comment by ALENBERG1** [comment]
same as aladin221

**Comment by vBlackOut** [comment]
check my update for resolve your problem

**Comment by ALENBERG1** [comment]
ok now it work but if i put "False" in "use booster" in config file the bot continue to use the boosters

**Comment by vBlackOut** [comment]
ok i'm check

**Comment by ALENBERG1** [comment]
and can i ask you a question?

**Comment by vBlackOut** [comment]
yes

**Comment by ALENBERG1** [comment]
the bot upgrade only the firewall, can you put that you can choose what upgrade?

**Comment by vBlackOut** [comment]
just complet list is inet, hdd, cpu, ram, fw, av, sdk, ipsp, spam, scan, adw
for all item

**Comment by ALENBERG1** [comment]
like this?

[Config]
maxanti_normal: 3000
maxanti_tournament: 3000
booster: False
Use_netcoins: False
attacks_normal: 3
attacks_tournament: 2
tournament_potator: True
update: fw
update: av
update: sdk
update: ipsp
update: spam
update: scan
update: adw
join_tournament: True
mode: Potator
Botnet_update: True

**Comment by vBlackOut** [comment]
nop , just 
update: inet, hdd, cpu, ram, fw, av, sdk, ipsp, spam, scan, adw
in the one line

**Comment by ALENBERG1** [comment]
ok thank you, can we keep in touch?

**Comment by vBlackOut** [comment]
no problem yes ;)

**Comment by ALENBERG1** [comment]
thank you, i'm alenberg#9617 on discord :)

**Comment by vBlackOut** [comment]
ok no problem :)
